/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ServicosRouteImport } from './routes/servicos'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RelatoriosRouteImport } from './routes/relatorios'
import { Route as RecuperarSenhaRouteImport } from './routes/recuperar-senha'
import { Route as QuizRouteImport } from './routes/quiz'
import { Route as PlaybookRouteImport } from './routes/playbook'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FinanceiroRouteImport } from './routes/financeiro'
import { Route as EstoqueRouteImport } from './routes/estoque'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as AlertasRouteImport } from './routes/alertas'
import { Route as AgendaRouteImport } from './routes/agenda'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VeiculosIndexRouteImport } from './routes/veiculos.index'
import { Route as OsIndexRouteImport } from './routes/os.index'
import { Route as ClientesIndexRouteImport } from './routes/clientes.index'
import { Route as VeiculosVehicleIdRouteImport } from './routes/veiculos.$vehicleId'
import { Route as OsNovaRouteImport } from './routes/os.nova'
import { Route as OsKanbanRouteImport } from './routes/os.kanban'
import { Route as OsOsIdRouteImport } from './routes/os.$osId'
import { Route as ConviteTokenRouteImport } from './routes/convite.$token'
import { Route as ClientesClientIdRouteImport } from './routes/clientes.$clientId'
import { Route as OsOsIdEditarRouteImport } from './routes/os.$osId.editar'

const ServicosRoute = ServicosRouteImport.update({
  id: '/servicos',
  path: '/servicos',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RelatoriosRoute = RelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => rootRouteImport,
} as any)
const RecuperarSenhaRoute = RecuperarSenhaRouteImport.update({
  id: '/recuperar-senha',
  path: '/recuperar-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizRoute = QuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaybookRoute = PlaybookRouteImport.update({
  id: '/playbook',
  path: '/playbook',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceiroRoute = FinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => rootRouteImport,
} as any)
const EstoqueRoute = EstoqueRouteImport.update({
  id: '/estoque',
  path: '/estoque',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertasRoute = AlertasRouteImport.update({
  id: '/alertas',
  path: '/alertas',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendaRoute = AgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VeiculosIndexRoute = VeiculosIndexRouteImport.update({
  id: '/veiculos/',
  path: '/veiculos/',
  getParentRoute: () => rootRouteImport,
} as any)
const OsIndexRoute = OsIndexRouteImport.update({
  id: '/os/',
  path: '/os/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesIndexRoute = ClientesIndexRouteImport.update({
  id: '/clientes/',
  path: '/clientes/',
  getParentRoute: () => rootRouteImport,
} as any)
const VeiculosVehicleIdRoute = VeiculosVehicleIdRouteImport.update({
  id: '/veiculos/$vehicleId',
  path: '/veiculos/$vehicleId',
  getParentRoute: () => rootRouteImport,
} as any)
const OsNovaRoute = OsNovaRouteImport.update({
  id: '/os/nova',
  path: '/os/nova',
  getParentRoute: () => rootRouteImport,
} as any)
const OsKanbanRoute = OsKanbanRouteImport.update({
  id: '/os/kanban',
  path: '/os/kanban',
  getParentRoute: () => rootRouteImport,
} as any)
const OsOsIdRoute = OsOsIdRouteImport.update({
  id: '/os/$osId',
  path: '/os/$osId',
  getParentRoute: () => rootRouteImport,
} as any)
const ConviteTokenRoute = ConviteTokenRouteImport.update({
  id: '/convite/$token',
  path: '/convite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesClientIdRoute = ClientesClientIdRouteImport.update({
  id: '/clientes/$clientId',
  path: '/clientes/$clientId',
  getParentRoute: () => rootRouteImport,
} as any)
const OsOsIdEditarRoute = OsOsIdEditarRouteImport.update({
  id: '/editar',
  path: '/editar',
  getParentRoute: () => OsOsIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/alertas': typeof AlertasRoute
  '/cadastro': typeof CadastroRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/estoque': typeof EstoqueRoute
  '/financeiro': typeof FinanceiroRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/playbook': typeof PlaybookRoute
  '/quiz': typeof QuizRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/relatorios': typeof RelatoriosRoute
  '/reset-password': typeof ResetPasswordRoute
  '/servicos': typeof ServicosRoute
  '/clientes/$clientId': typeof ClientesClientIdRoute
  '/convite/$token': typeof ConviteTokenRoute
  '/os/$osId': typeof OsOsIdRouteWithChildren
  '/os/kanban': typeof OsKanbanRoute
  '/os/nova': typeof OsNovaRoute
  '/veiculos/$vehicleId': typeof VeiculosVehicleIdRoute
  '/clientes/': typeof ClientesIndexRoute
  '/os/': typeof OsIndexRoute
  '/veiculos/': typeof VeiculosIndexRoute
  '/os/$osId/editar': typeof OsOsIdEditarRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/alertas': typeof AlertasRoute
  '/cadastro': typeof CadastroRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/estoque': typeof EstoqueRoute
  '/financeiro': typeof FinanceiroRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/playbook': typeof PlaybookRoute
  '/quiz': typeof QuizRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/relatorios': typeof RelatoriosRoute
  '/reset-password': typeof ResetPasswordRoute
  '/servicos': typeof ServicosRoute
  '/clientes/$clientId': typeof ClientesClientIdRoute
  '/convite/$token': typeof ConviteTokenRoute
  '/os/$osId': typeof OsOsIdRouteWithChildren
  '/os/kanban': typeof OsKanbanRoute
  '/os/nova': typeof OsNovaRoute
  '/veiculos/$vehicleId': typeof VeiculosVehicleIdRoute
  '/clientes': typeof ClientesIndexRoute
  '/os': typeof OsIndexRoute
  '/veiculos': typeof VeiculosIndexRoute
  '/os/$osId/editar': typeof OsOsIdEditarRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/alertas': typeof AlertasRoute
  '/cadastro': typeof CadastroRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/estoque': typeof EstoqueRoute
  '/financeiro': typeof FinanceiroRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/playbook': typeof PlaybookRoute
  '/quiz': typeof QuizRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/relatorios': typeof RelatoriosRoute
  '/reset-password': typeof ResetPasswordRoute
  '/servicos': typeof ServicosRoute
  '/clientes/$clientId': typeof ClientesClientIdRoute
  '/convite/$token': typeof ConviteTokenRoute
  '/os/$osId': typeof OsOsIdRouteWithChildren
  '/os/kanban': typeof OsKanbanRoute
  '/os/nova': typeof OsNovaRoute
  '/veiculos/$vehicleId': typeof VeiculosVehicleIdRoute
  '/clientes/': typeof ClientesIndexRoute
  '/os/': typeof OsIndexRoute
  '/veiculos/': typeof VeiculosIndexRoute
  '/os/$osId/editar': typeof OsOsIdEditarRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agenda'
    | '/alertas'
    | '/cadastro'
    | '/configuracoes'
    | '/estoque'
    | '/financeiro'
    | '/login'
    | '/onboarding'
    | '/playbook'
    | '/quiz'
    | '/recuperar-senha'
    | '/relatorios'
    | '/reset-password'
    | '/servicos'
    | '/clientes/$clientId'
    | '/convite/$token'
    | '/os/$osId'
    | '/os/kanban'
    | '/os/nova'
    | '/veiculos/$vehicleId'
    | '/clientes/'
    | '/os/'
    | '/veiculos/'
    | '/os/$osId/editar'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agenda'
    | '/alertas'
    | '/cadastro'
    | '/configuracoes'
    | '/estoque'
    | '/financeiro'
    | '/login'
    | '/onboarding'
    | '/playbook'
    | '/quiz'
    | '/recuperar-senha'
    | '/relatorios'
    | '/reset-password'
    | '/servicos'
    | '/clientes/$clientId'
    | '/convite/$token'
    | '/os/$osId'
    | '/os/kanban'
    | '/os/nova'
    | '/veiculos/$vehicleId'
    | '/clientes'
    | '/os'
    | '/veiculos'
    | '/os/$osId/editar'
  id:
    | '__root__'
    | '/'
    | '/agenda'
    | '/alertas'
    | '/cadastro'
    | '/configuracoes'
    | '/estoque'
    | '/financeiro'
    | '/login'
    | '/onboarding'
    | '/playbook'
    | '/quiz'
    | '/recuperar-senha'
    | '/relatorios'
    | '/reset-password'
    | '/servicos'
    | '/clientes/$clientId'
    | '/convite/$token'
    | '/os/$osId'
    | '/os/kanban'
    | '/os/nova'
    | '/veiculos/$vehicleId'
    | '/clientes/'
    | '/os/'
    | '/veiculos/'
    | '/os/$osId/editar'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgendaRoute: typeof AgendaRoute
  AlertasRoute: typeof AlertasRoute
  CadastroRoute: typeof CadastroRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  EstoqueRoute: typeof EstoqueRoute
  FinanceiroRoute: typeof FinanceiroRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  PlaybookRoute: typeof PlaybookRoute
  QuizRoute: typeof QuizRoute
  RecuperarSenhaRoute: typeof RecuperarSenhaRoute
  RelatoriosRoute: typeof RelatoriosRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ServicosRoute: typeof ServicosRoute
  ClientesClientIdRoute: typeof ClientesClientIdRoute
  ConviteTokenRoute: typeof ConviteTokenRoute
  OsOsIdRoute: typeof OsOsIdRouteWithChildren
  OsKanbanRoute: typeof OsKanbanRoute
  OsNovaRoute: typeof OsNovaRoute
  VeiculosVehicleIdRoute: typeof VeiculosVehicleIdRoute
  ClientesIndexRoute: typeof ClientesIndexRoute
  OsIndexRoute: typeof OsIndexRoute
  VeiculosIndexRoute: typeof VeiculosIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/servicos': {
      id: '/servicos'
      path: '/servicos'
      fullPath: '/servicos'
      preLoaderRoute: typeof ServicosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relatorios': {
      id: '/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof RelatoriosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recuperar-senha': {
      id: '/recuperar-senha'
      path: '/recuperar-senha'
      fullPath: '/recuperar-senha'
      preLoaderRoute: typeof RecuperarSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz': {
      id: '/quiz'
      path: '/quiz'
      fullPath: '/quiz'
      preLoaderRoute: typeof QuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playbook': {
      id: '/playbook'
      path: '/playbook'
      fullPath: '/playbook'
      preLoaderRoute: typeof PlaybookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financeiro': {
      id: '/financeiro'
      path: '/financeiro'
      fullPath: '/financeiro'
      preLoaderRoute: typeof FinanceiroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estoque': {
      id: '/estoque'
      path: '/estoque'
      fullPath: '/estoque'
      preLoaderRoute: typeof EstoqueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alertas': {
      id: '/alertas'
      path: '/alertas'
      fullPath: '/alertas'
      preLoaderRoute: typeof AlertasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agenda': {
      id: '/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AgendaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/veiculos/': {
      id: '/veiculos/'
      path: '/veiculos'
      fullPath: '/veiculos/'
      preLoaderRoute: typeof VeiculosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/os/': {
      id: '/os/'
      path: '/os'
      fullPath: '/os/'
      preLoaderRoute: typeof OsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes/': {
      id: '/clientes/'
      path: '/clientes'
      fullPath: '/clientes/'
      preLoaderRoute: typeof ClientesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/veiculos/$vehicleId': {
      id: '/veiculos/$vehicleId'
      path: '/veiculos/$vehicleId'
      fullPath: '/veiculos/$vehicleId'
      preLoaderRoute: typeof VeiculosVehicleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/os/nova': {
      id: '/os/nova'
      path: '/os/nova'
      fullPath: '/os/nova'
      preLoaderRoute: typeof OsNovaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/os/kanban': {
      id: '/os/kanban'
      path: '/os/kanban'
      fullPath: '/os/kanban'
      preLoaderRoute: typeof OsKanbanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/os/$osId': {
      id: '/os/$osId'
      path: '/os/$osId'
      fullPath: '/os/$osId'
      preLoaderRoute: typeof OsOsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/convite/$token': {
      id: '/convite/$token'
      path: '/convite/$token'
      fullPath: '/convite/$token'
      preLoaderRoute: typeof ConviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes/$clientId': {
      id: '/clientes/$clientId'
      path: '/clientes/$clientId'
      fullPath: '/clientes/$clientId'
      preLoaderRoute: typeof ClientesClientIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/os/$osId/editar': {
      id: '/os/$osId/editar'
      path: '/editar'
      fullPath: '/os/$osId/editar'
      preLoaderRoute: typeof OsOsIdEditarRouteImport
      parentRoute: typeof OsOsIdRoute
    }
  }
}

interface OsOsIdRouteChildren {
  OsOsIdEditarRoute: typeof OsOsIdEditarRoute
}

const OsOsIdRouteChildren: OsOsIdRouteChildren = {
  OsOsIdEditarRoute: OsOsIdEditarRoute,
}

const OsOsIdRouteWithChildren =
  OsOsIdRoute._addFileChildren(OsOsIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgendaRoute: AgendaRoute,
  AlertasRoute: AlertasRoute,
  CadastroRoute: CadastroRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  EstoqueRoute: EstoqueRoute,
  FinanceiroRoute: FinanceiroRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  PlaybookRoute: PlaybookRoute,
  QuizRoute: QuizRoute,
  RecuperarSenhaRoute: RecuperarSenhaRoute,
  RelatoriosRoute: RelatoriosRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ServicosRoute: ServicosRoute,
  ClientesClientIdRoute: ClientesClientIdRoute,
  ConviteTokenRoute: ConviteTokenRoute,
  OsOsIdRoute: OsOsIdRouteWithChildren,
  OsKanbanRoute: OsKanbanRoute,
  OsNovaRoute: OsNovaRoute,
  VeiculosVehicleIdRoute: VeiculosVehicleIdRoute,
  ClientesIndexRoute: ClientesIndexRoute,
  OsIndexRoute: OsIndexRoute,
  VeiculosIndexRoute: VeiculosIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
